export interface Element {
    tagName: string;
    properties: any;
    children: Element[];
}
export declare const h1: (properties?: {}, children?: any[]) => Element;
export declare const h2: (properties?: {}, children?: any[]) => Element;
export declare const h3: (properties?: {}, children?: any[]) => Element;
export declare const hr: (properties?: {}, children?: any[]) => Element;
export declare const a: (properties?: {}, children?: any[]) => Element;
export declare const p: (properties?: {}, children?: any[]) => Element;
export declare const div: (properties?: {}, children?: any[]) => Element;
export declare const span: (properties?: {}, children?: any[]) => Element;
export declare const ul: (properties?: {}, children?: any[]) => Element;
export declare const li: (properties?: {}, children?: any[]) => Element;
export declare const form: (properties?: {}, children?: any[]) => Element;
export declare const input: (properties?: {}, children?: any[]) => Element;
export declare const button: (properties?: {}, children?: any[]) => Element;
export declare const select: (properties?: {}, children?: any[]) => Element;
export declare const label: (properties?: {}, children?: any[]) => Element;
export declare const fieldset: (properties?: {}, children?: any[]) => Element;
export declare const body: (properties?: {}, children?: any[]) => Element;
export declare const section: (properties?: {}, children?: any[]) => Element;
export declare const header: (properties?: {}, children?: any[]) => Element;
export declare const footer: (properties?: {}, children?: any[]) => Element;
export declare const main: (properties?: {}, children?: any[]) => Element;
export declare const canvas: (properties?: {}, children?: any[]) => Element;
export declare const textBox: (name: string, value: string) => Element;
export declare const link: (href: string, text: string) => Element;
export declare const buildFormField: (field: any) => Element;
